# -*- coding: utf-8 -*-
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=9#&u(q&4vcq=s+b&9&3r%fgj4695%7ff6mx39)mmwk#v)z97%'


MULTITENANT_MAPPER_CLASS = 'tenant.mapper.TenantMapper'
#MULTI_TENANT_MODE = 'SCHEMA' #DATABASE
#DEFAULT_TENANT_NAME = "devnull" #default


#DATABASE_ROUTERS = ['db_multitenant.router.DatabaseRouter']

# Application definition

INSTALLED_APPS = (
    #'django_admin_bootstrapped',
    'suit',
    'salmonella',
    'autocomplete_light',
    'django.contrib.admin.apps.SimpleAdminConfig',  # instead of 'django.contrib.admin'
    'apps.GypsyAuthConfig',#'django.contrib.auth',
    #'django.contrib.admindocs',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #"tenant",
    'demande',
    'fusion',
    'adminplus',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware'
)

#MIDDLEWARE_CLASSES = (
#    'db_multitenant.middleware.MultiTenantSchemaMiddleware',
#    #'db_multitenant.middleware.MultiTenantDatabaseMiddleware',
#) + MIDDLEWARE_CLASSES

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'mysite.wsgi.application'


FILE_SYSTEM_HOME= BASE_DIR + "/"
FILE_SYSTEM_DOCS=  BASE_DIR + "/print"
FILE_SYSTEM_TMP="C:/tmp/"
#FILE_SYSTEM_TMP="/tmp/"
FILE_OUT_DOC = FILE_SYSTEM_HOME + "/media/upload/out/"


# Pour l'upload des static
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/


#LANGUAGE_CODE = 'en-us'
#LANGUAGE_CODE = 'ar-DZ'
LANGUAGE_CODE = 'fr-FR'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")


from django.utils.translation import ugettext_lazy as _

SUIT_CONFIG = {
     # header
     'ADMIN_NAME': 'Mon application',
     'HEADER_DATE_FORMAT': 'l, j. F Y',
     'HEADER_TIME_FORMAT': 'H:i',

     # forms
     'SHOW_REQUIRED_ASTERISK': True,  # Default True
     'CONFIRM_UNSAVED_CHANGES': True, # Default True

     # menu
     # 'SEARCH_URL': '/admin/auth/user/',
     # 'MENU_ICONS': {
     #    'sites': 'icon-leaf',
     #    'auth': 'icon-lock',
     # },
     # 'MENU_OPEN_FIRST_CHILD': True, # Default True
     #'MENU_OPEN_FIRST_CHILD': False,

     #'MENU_EXCLUDE': ('auth.group', 'auth.user'),
     'MENU': (

        # Cross-linked models with custom name; Hide default icon
        {'label': _('Acces'), 'icon': 'icon-lock', 'permissions': ('auth.add_user', 'auth.change_user'),
        'models': (
            {'model': 'auth.user', 'label': _('Utilisateurs')},
            {'model': 'auth.group', 'label': _('Groupes')}
        )},

        {'label': 'Demande', 'icon':'icon-chevron-right', 
        'models': (
            {'model': 'demande.task', 'label': _('Task'), 'permissions': ('demande.add_task')},
        )},

        {'label': _('Modeles'), 'icon':'icon-chevron-right', 'url': 'admin:fusion_document_changelist', 'permissions': ('fusion.add_document')},

    
        #{'app': 'auth', 'models': ('user', 'group')},
        #{'label': 'database', 'icon':'icon-chevron-right', 'models': ('database.book', 'database.advert',)},
        #{'label': 'vente', 'icon':'icon-chevron-right', 'models': ('vente.order', 'vente.item')},
        #{'label': 'Tableau de bord', 'icon':'icon-question-sign', 'url': 'admin:dash'},
    ),

    # misc
     'LIST_PER_PAGE': 10
}
